language: node_js
sudo: false
node_js:
  - 10
  
language: python
python:
  - 3.6 
  
addons:
  chrome: stable
install:
  #- npm install

  - pip install selenium
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
  - cd autotests
  - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

  - ls
  - pwd

  
script:
- whereis google-chrome-stable
- whereis chromedriver
- DISPLAY=:99 xvfb-run -a -n 1 -l -s "-screen 0, 1024x768x8"
- python main.py
