language: node_js
sudo: false
node_js:
  - 10
  
language: python
python:
  - 3.6 
  
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits)
  - npm install
#  - npm run serve
#  - pip install --upgrade pip
  - pip install selenium
  
  - cd autotests
  - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
#  - sudo mv -f ~/chromedriver /usr/local/share/
#  - mv chromedriver_linux64/chromedriver.exe ../
  - ls
#  - sudo chmod +x /usr/local/share/chromedriver
#  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

  
script:
- whereis google-chrome-stable
- whereis chromedriver
- cd autotests & python main.py
